version: '3.6'

services:
  backend:
    build:
      context: .
      dockerfile: personnel_server/dockerfile
    ports:
      - "3001:3001"
    environment:
      # DATABASE_HOST: 212.111.203.178
      DATABASE_HOST: 172.16.1.35
      DATABASE_PORT: 3306
      DATABASE_USERNAME: keeper
      DATABASE_PASSWORD: 'toor!'
      DATABASE_NAME: kadry
    volumes:
      - ./personnel_server:/usr/backend/
      - /home/keeper/backups:/tmp/backups
    restart: 'always'

  front:
    build: 
      context: .
      dockerfile: front/dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./front:/usr/front/
    restart: 'always'
  
  bot:
    build:
      context: ./bot
      dockerfile: Dockerfile
    environment:
      TELEGRAM_TOKEN: ${TELEGRAM_TOKEN}
      TELEGRAM_CHAT_ID: ${TELEGRAM_ID}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      
volumes:
  mysql_data:



