version: '3.6'

services:
  backend:
    build:
      context: .
      dockerfile: personnel_server/dockerfile
    ports:
      - "127.0.0.1:3001:3001"
    environment:
      DATABASE_PORT: 3306
      DATABASE_USERNAME: keeper
      DATABASE_PASSWORD: 'toor!'
      DATABASE_NAME: kadry
    volumes:
      - ./personnel_server:/usr/backend/
      - /home/keeper/backups:/tmp/backups
    restart: 'always'

  front:
    build: 
      context: .
      dockerfile: front/dockerfile
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - ./front:/usr/front/
    restart: 'always'
  
  bot:
    build:
      context: ./bot
      dockerfile: Dockerfile
    env_file:
      - ./bot/.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: 'always'
      
volumes:
  mysql_data:



