version: '3.6'

services:
  mysql:
    image: mysql:8.0
    environment:
        MYSQL_ROOT_PASSWORD: toor
        MYSQL_DATABASE: kadry
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: .
    ports:
      - '3001:3001'
    depends_on:
      - mysql
    environment:
      DATABASE_HOST: localhost
      DATABASE_PORT: 3306
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: toor
      DATABASE_NAME: kadry
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: sh -c "sleep 10 && npm start"

volumes:
  mysql_data: