version: '3.8'

services:
  app:
    build: .
    ports:
      - "3001:3001"
    depends_on:
      - db
    environment:
      - DATABASE_URL=mysql://root:toor@db:3306/kadry

  db: 
    image: mysql:8.0
    environment:
      - MYSQL_PASS='toor'
      - MYSQL_DB='kadry'
      - MYSQL_USER='root'
      - MYSQL_PASSWORD='toor'
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:

