version: '3.6'

services:
  mysql:
    image: mysql:8.0
    environment:
        MYSQL_ROOT_PASSWORD: toor
        MYSQL_DATABASE: kadry
    ports:
      - '3307:3306'
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build:
      context: ./personnel_server
      dockerfile: ./personnel_server/dockerfile
    ports:
      - '3001:3001'
    depends_on:
      - mysql
    environment:
      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: toor
      DATABASE_NAME: kadry
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    
  front:
    build: 
      context: ./front
      dockerfile: ./front/dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./front:/usr/src/front
      - /usr/src/front/node_modules
    
  nginx:
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
      - front
      
volumes:
  mysql_data: