version: '3.6'

services:
  # mysql:
  #   image: mysql:8.0.36
  #   environment:
  #       MYSQL_DATABASE: kadry
  #   ports:
  #     - '3307:3306'
  #   volumes:
  #     - mysql_data:/var/lib/mysql
  #   restart: 'always'

  backend:
    build:
      context: .
      dockerfile: personnel_server/dockerfile
    ports:
      - "3001:3001"
    environment:
      DATABASE_HOST: 212.111.203.178
      DATABASE_PORT: 3306
      DATABASE_USERNAME: keeper 
      DATABASE_PASSWORD: 'toor!'
      DATABASE_NAME: kadry
    volumes:
      - ./personnel_server:/usr/backend/
      - /home/keeper/backups:/tmp/backups
    restart: 'always'

  front:
    build: 
      context: .
      dockerfile: front/dockerfile
    ports:
      - "4000:4000"
    volumes:
      - ./front:/usr/front/
    restart: 'always'
    
volumes:
  mysql_data:



# DATABASE_URL: mysql://keeper:toor%21@172.16.1.35:3306/kadry
