version: '3.6'

services:
  backend:
    build:
      context: .
      dockerfile: personnel_server/dockerfile
    ports:
      - "0.0.0.0:3001:3001"
    environment:
      DATABASE_PORT: 3306
      DATABASE_USERNAME: keeper
      DATABASE_PASSWORD: 'toor!'
      DATABASE_NAME: kadry
    volumes:
      - ./personnel_server:/usr/backend/
      - /home/keeper/backups:/tmp/backups
    restart: 'always'

  front:
    build: 
      context: .
      dockerfile: front/dockerfile
    ports:
      - "0.0.0.0:3000:3000"
    volumes:
      - ./front:/usr/front/
    restart: 'always'
      
volumes:
  mysql_data:



