version: '3.6'

services:
  mysql:
    image: mysql:latest
    environment:
        MYSQL_ROOT_PASSWORD: toor
        MYSQL_DATABASE: kadry
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    restart: 'always'

  backend:
    build:
      context: .
      dockerfile: personnel_server/dockerfile
    ports:
      - "3001:3001"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/kadry
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: rootpassword
    volumes:
      - ./personnel_server:/usr/backend/
    restart: 'always'

  front:
    build: 
      context: .
      dockerfile: front/dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./front:/usr/front/
    restart: 'always'
    
volumes:
  mysql_data: