version: '3.6'

services:
  mysql:
    image: mysql:latest
    environment:
        MYSQL_ROOT_PASSWORD: toor
        MYSQL_DATABASE: kadry
    ports:
      - '3307:3306'
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build:
      context: .
      dockerfile: personnel_server/dockerfile
    ports:
      - '3001:3001'
    depends_on:
      - mysql
    environment:
      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: toor
      DATABASE_NAME: kadry
    volumes:
      - ./personnel_server:/usr/backend/
    
  front:
    build: 
      context: .
      dockerfile: front/dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./front:/usr/front/
    
  nginx:
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
      - front
      
volumes:
  mysql_data: