FROM node:21-alpine
RUN apt-get update && apt-get install -y p7zip-full
WORKDIR /backend
COPY personnel_server/package*.json ./
RUN npm install
COPY personnel_server/ .
RUN npm run build
EXPOSE 3001
CMD ["npm", "start"]