FROM node:21-alpine
RUN apk --no-cache update && apk add --no-cache p7zip
WORKDIR /backend
COPY personnel_server/package*.json ./
RUN npm install
COPY personnel_server/ .
RUN npm run build
EXPOSE 3001
CMD ["npm", "start"]