FROM node:20

RUN apt-get update && \
    apt-get install -y \
    libgtk-3-dev \
    libx11-xcb-dev \
    libgconf-2-4 \
    libnss3 \
    libasound2 \
    libxtst6 \
    libxkbcommon-x11-0 \
    libxss1 \
    libxrandr2 \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /electron
COPY desktop/package*.json ./
RUN npm install
COPY desktop/ .
CMD [ "npm", "start" ]